### PR TITLE
Added mermaid graph support.

### PR DESCRIPTION
**Pull request by djmittens**
Also replaced syntax highlighting with prism, which i thought would be neat.

I dont know how useful this might be for others, but it sure as heck made my life easier.

### CODE REVIEW

**Comment by djmittens** [comment]
Any updates on this? would be cool if my chrome extension got an update without me having to checkout my repository every time.

**Comment by volca** [comment]
Sorry. I will merge it today.

**Comment by volca** [comment]
It works very good. The only problem is the font color is so bright when theme is "Clearness" or "Github".

**Comment by volca** [comment]
Sorry. I must rollback to previous version 0.4 because the issue #14. It's difficult to use now.

**Pull request merged**
